
stages:
  - build
  - doc
  - test

build-cpp-deps:
  stage: build
  only:
    refs:
    - cpp-deps
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
      # Tag images with git commit SHAs
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile build/cpp-deps.Dockerfile --destination $CI_REGISTRY_IMAGE/cpp-deps:latest --destination $CI_REGISTRY_IMAGE/cpp-deps:$CI_COMMIT_SHORT_SHA --build-arg CPP_DEPS_COMMIT=$CI_COMMIT_SHORT_SHA -v warn

build-rust-deps:
  stage: build
  only:
    refs:
    - rust-deps
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
      # Tag images with git commit SHAs
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile build/rust-deps.Dockerfile --destination $CI_REGISTRY_IMAGE/rust-deps:latest --destination $CI_REGISTRY_IMAGE/rust-deps:$CI_COMMIT_SHORT_SHA --build-arg RUST_DEPS_COMMIT=$CI_COMMIT_SHORT_SHA -v warn

build-image:
  stage: build
  needs: []
  except:
    refs:
    - cpp-deps
    - rust-deps
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
      # Tag images with git commit SHAs
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile build/main.Dockerfile --destination $CI_REGISTRY_IMAGE:latest --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --build-arg SRC_COMMIT=$CI_COMMIT_SHORT_SHA -v warn

# https://users.rust-lang.org/t/my-gitlab-config-docs-tests/16396
pages:
  stage: doc
  needs: []
  image: $CI_REGISTRY_IMAGE/rust-deps
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url={{ LIBRARY NAME }}">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - main

test:
  stage: test
  needs: []
  image:
    name: $CI_REGISTRY_IMAGE/rust-deps
  script:
    - rustc --version
    - cargo --version
    - cargo test --release --verbose
