[package]
name = "posenet-vr-hub"
version = "0.1.0"
authors = ["Oliver Evans <oliverevans96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cxx = "1.0"
cxx = {path = "/home/oliver/code/rust/cxx"}
nalgebra = "0.24"
generic-array = "0.14"
tonic = "0.3"
prost = "0.6"
tokio = {version = "0.2", features=["macros", "time"]}
futures = { version = "0.3", default-features = false, features = ["alloc"] }
async-std = "1.9"
rand = "0.8"

[build-dependencies]
tonic-build = "0.3"
cxx-build = "1.0"
dotenv = "0.15"