---
# NOTE: The pod needs to be restarted to observe
# changes in the NGINX config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posenet-hub-docs-nginx
  namespace: posenet
  labels:
    app: nginx
    subject: posenet-hub-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      subject: posenet-hub-docs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        subject: posenet-hub-docs
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: posenet-docs-nginx-config
        - name: rclone-config
          secret:
            secretName: ceph-s3-rclone-conf
        - name: shared-volume
          emptyDir: {}

      containers:
        - name: rclone
          image: rclone/rclone
          imagePullPolicy: IfNotPresent

          command: ["watch", "-n", "60", "rclone", "sync", "ceph-s3:posenet-hub-docs", "/ceph"]

          resources:
            limits:
              memory: 1Gi
              cpu: "1"
            requests:
              memory: 1Gi
              cpu: "1"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: shared-volume
              mountPath: /ceph
            - name: rclone-config
              mountPath: /config/rclone

        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 4Gi
              cpu: "2"
            requests:
              memory: 1Gi
              cpu: "1"

          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: shared-volume
              mountPath: /var/www

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: posenet-docs-nginx-config
data:
  # Inspired by:
  # - https://www.netnea.com/cms/nginx-tutorial-2_minimal-nginx-configuration/
  # - http://nginx.org/en/docs/beginners_guide.html#static
  # - https://www.nginx.com/resources/wiki/start/topics/examples/full/
  # - https://blog.gastove.com/blog/2020-05-30--self-hosting-rust
  nginx.conf: |-
    worker_processes  2;
    user              www-data;

    events {
        use           epoll;
        worker_connections  128;
    }

    http {
      server { # simple reverse-proxy
        listen       80;
        server_name  posenet-hub-docs.nrp-nautilus.io;

        location / {
          root /var/www;
          include  /etc/nginx/mime.types;
          rewrite ^/$ posenet_vr_hub/index.html redirect;
        }
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: posenet-hub-docs-nginx
  namespace: posenet
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx
    subject: posenet-hub-docs

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
  name: posenet-hub-docs
  namespace: posenet
spec:
  rules:
  - host: posenet-hub-docs.nrp-nautilus.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: posenet-hub-docs-nginx
            port:
              number: 80
  tls:
  - hosts:
    - posenet-hub-docs.nrp-nautilus.io