---
apiVersion: v1
kind: Service
metadata:
  name: posenet-hub-tcp
  namespace: posenet
  labels:
    app: posenet-hub
  annotations:
    metallb.universe.tf/allow-shared-ip: "posenet-hub"
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
    - name: vrpn
      port: 3083
      targetPort: 3038
      protocol: TCP
  type: LoadBalancer
#  loadBalancerIP: 67.58.49.50
  selector:
    app: posenet-hub
---
apiVersion: v1
kind: Service
metadata:
  name: posenet-hub-udp
  namespace: posenet
  labels:
    app: posenet-hub
  annotations:
    metallb.universe.tf/allow-shared-ip: "posenet-hub"
spec:
  ports:
    - name: vrpn
      port: 3083
      targetPort: 3038
      protocol: UDP
  type: LoadBalancer
#  loadBalancerIP: 67.58.49.50
  selector:
    app: posenet-hub
