//! Posenet Hub serves virtual VR controller over VRPN generated by reconstructing
//! 3D poses based on 2D poses infered from posenet multiple camera angles.
//! I'm going to improve this documentation.
//! https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html

pub mod controller;
pub mod errors;
pub mod grpc;
pub mod http_server;
pub mod openmvg;
pub mod recording;
pub mod synthetic_cameras;
pub mod triangulator;
mod utils;
pub mod vrpn;
pub mod websocket;

// Re-export common error types for library consumers and binaries
pub use errors::{CalculationError, ConfigError, HubError, MissingField, OpenMvgError};
